# Default values for mod-entities-links.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: folioorg/mod-entities-links
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

replicaCount: 1

resources:
  limits:
    # cpu: 100m
    memory: 512Mi
  requests:
    # cpu: 50m
    memory: 384Mi

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 4
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Should be set to NodePort if ingress for AWS ALB enabled
service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      containerPort: 8081
      targetPort: http
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /*
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

args: []

eureka:
  enabled: false
  envVars: []
  # - name: FOO
  #   value: ba
  extraEnvVars: []
  # - name: FOO
  #   value: ba

## @param javaOpts Custom JVM parameters
##
javaOpts: []

extraJavaOpts:
  - "-XX:MaxRAMPercentage=75.0"
  # - "-Dlog_level=DEBUG"

envVars:
  - name: KAFKA_PRODUCER_TENANT_COLLECTION
    value: "ALL"

extraEnvVars: []
  # - name: FOO
  #   value: bar

extraEnvVarsSecrets: []
  # = foo-secret
  # - bar-secret

jmx:
  enabled: false
  port: 1099

heapDumpEnabled: false

volumeClaims:
  extendedtmp:
    enabled: false
    name: &extendedtmp_name '{{ printf "%s-%s" (include "folio-common.fullname" $) "extendedtmp" }}'
    storageClassName: gp2
    size: 20Gi
    accessModes: ReadWriteOnce
    existingClaim:

extraVolumeMounts:
  heapdump:
    enabled: false
    name: heapdump
    mountPath: /tmp/dump
  extendedtmp:
    enabled: false
    name: extendedtmp
    mountPath: /tmp

extraVolumes:
  heapdump:
    enabled: false
    name: heapdump
    emptyDir: {}
  extendedtmp:
    enabled: false
    name: extendedtmp
    persistentVolumeClaim:
      claimName: *extendedtmp_name

initContainer:
  enabled: false
  image:
    repository: busybox
    registry: 732722833398.dkr.ecr.us-west-2.amazonaws.com
    tag: latest
    pullPolicy: IfNotPresent
    command: '["sh", "-c", "chown -R 1000:1000 /tmp"]'
  args:
  extraVolumeMounts:
    extendedtmp:
      enabled: false
      name: extendedtmp
      mountPath: /tmp

sidecarContainers:
  eureka:
    enabled: "{{ .Values.eureka.enabled }}"
    name: sidecar
    image:
      repository: folioorg/folio-module-sidecar
      pullPolicy: IfNotPresent
      tag: latest
    envVars:
      - '{{ include "folio-common.sidecar.env.eureka.common" . }}'
    extraEnvVars: []
      # - name: FOO
      #   value: bar
    ports:
      - name: sidecar
        protocol: TCP
        port: 8082
        containerPort: 8082
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi

integrations:
  okapi:
    enabled: true
    host: okapi
    port: 9130
    url: http://okapi:9130
    existingSecret: ""

  db:
    enabled: true
    host: postgresql
    hostReader: ""
    port: 5432
    database: folio
    username: admin
    password: password
    charset: UTF-8
    querytimeout: 60000
    maxpoolsize: 5
    existingSecret: ""

  kafka:
    enabled: true
    host: localhost
    port: 9092
    existingSecret: ""

  systemuser:
    enabled: true
    name: "mod-entities-links"
    password: ""
    existingSecret: ""

configMaps: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

startupProbe: {}
readinessProbe: {}
livenessProbe: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}

# Folio specific
javaOptions: -XX:MaxRAMPercentage=85.0 -XX:+UseG1GC
dbMaxPoolSize: 5

aws:
  url: us-east-2

bucket:
  name: folio-scout

# If need to create and attach ConfigMap add nedded parameters here
# And create folder configmaps. In folder create file with the same name that in this config.
# In file paste only data for configmap.
# config:
#   - name: sftp-config
#     subPath: users.conf
#     mountPath: /etc/sftp/users.conf

volumeMounts:
  # secrets:
  #   - name: secure-store-props
  #     mountPath: /etc/edge
  #     secretName: ephemeral-properties
  emptyDirs:
    - name: dumps-volume
      mountPath: /dumps

extraEnv: |
  - name: DB_MAXPOOLSIZE
    value: "{{ .Values.dbMaxPoolSize }}"
  - name: JAVA_OPTIONS
    value: {{ .Values.javaOptions }}
  - name: DB_QUERYTIMEOUT
    valueFrom:
      secretKeyRef:
        key: DB_QUERYTIMEOUT
        name: {{ .Values.dbConnectParameters }}
  - name: DB_CHARSET
    valueFrom:
      secretKeyRef:
        key: DB_CHARSET
        name: {{ .Values.dbConnectParameters }}

# Enable parameters for DB, Kafka or AWS connection. In value set name of secret
dbConnectParameters: db-connect-modules 
kafkaConnectParameters: db-connect-modules
awsConnectParameters: s3-credentials
okapiConnectParameters: db-connect-modules
systemUser: true

# initContainer:
#   image: 
#     repository: busybox
#     tag: latest
#   imagePullPolicy: Always
#   command: cat
#   overrideArgs:
#     - diku
#     - dkl
#   mountPath: /path

postJob:
  enabled: false
  okapiUrl: http://okapi:9130
  tenantId: diku
  sampleData: false
  referenceData: false
  image:
    repository: docker.dev.folio.org/folio-okapi-registration
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded

